<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="block newsletter">
    <div class="footer_newsletter">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('tm_newsletter_heading')->toHtml();?>
        <div class="news-right">
        <ul>
        	<li>
            	<div class="content">
            		<form class="form subscribe"
                        novalidate
                        action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
                        method="post"
                        data-mage-init='{"validation": {"errorClass": "mage-error"}}'
                        id="newsletter-validate-detail">
                        <div class="field newsletter">
                            <label class="label" for="newsletter"><span><?php /* @escapeNotVerified */ echo __('Sign Up for Our Newsletter:') ?></span></label>
                            <div class="control">
                                <input name="email" type="email" id="newsletter"
                                            placeholder="<?php /* @escapeNotVerified */ echo __('Enter your email address') ?>"
                                            data-validate="{required:true, 'validate-email':true}"/>
                                <span id="newsletter_error" class="error"></span>
                            </div>
                        </div>
                        <div class="actions">
                            <button id="subscribe_btn" class="action subscribe primary" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="button">
                                <span><?php /* @escapeNotVerified */ echo __('Subscribe') ?></span>
                            </button>
                        </div>
                    </form>
                </div>
        	</li>
    	</ul>
        </div>
	</div>
</div>

<div id="newsletter_form" style="display: none;" class="modal-opacity">
    <div class="modal">
        <!-- Modal content -->
        <div class="modal-content">
            <div class="modal-header">
                <span id="modal_close" class="close button-close">×</span>
                <h2>Newsletter Form</h2>
            </div>
            <div class="modal-body">
                
                    <form id="subForm" class="js-cm-form" action="https://www.createsend.com/t/subscribeerror?description=" method="post" data-id="30FEA77E7D0A9B8D7616376B90063231D2A618F0FC0F01C189E0372C5539C0CAE750127AB0676F2C48F0A1DE38A16F99B9C3201948A51E23C45FB6D9E67F4EBD">
                    <div class="input-fields">
                        <label for="fieldName">Name</label>
                        <input id="fieldName" name="cm-name" type="text" />
                    </div>
                    <div class="input-fields">
                        <label for="fieldEmail">Email</label>
                        <input id="fieldEmail" name="cm-zhkhud-zhkhud" type="email" class="js-cm-email-input" required />
                    </div>
                    <div class="input-fields">
                        <label>Opt into another list</label>
                        <div>
                            <input id="listahlurt" name="cm-ol-ahlurt" type="checkbox" />
                            <label for="listahlurt">Lombart Used Equipment - Weekly Notifications</label>
                        </div>
                    </div>
                    <div class="input-button">
                        <button class="button-close" type="button">Cancel</button>
                        <button class="js-cm-submit-button" type="submit">Subscribe</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="https://js.createsend1.com/javascript/copypastesubscribeformlogic.js"></script>

<script type="text/javascript">
    
    require(['jquery', 'jquery/ui'], function($){
        $("#subscribe_btn").click( function() {

            var email = $('#newsletter').val();

            if(!email){
                $('#newsletter_error').html('<div for="newsletter" generated="true" class="mage-error" id="newsletter-error">Please enter email address.</div>');
            }else{
                if(!isValidEmailAddress(email)){
                    $('#newsletter_error').html('<div for="newsletter" generated="true" class="mage-error" id="newsletter-error">Please enter a valid email address.</div>');
                }else{
                    $('#newsletter_error').html('');
                    $('#newsletter_form').show();
                    $('#fieldEmail').val(email);
                }
            }

        });

        $(".button-close").click( function() {
            $('#newsletter_form').hide();
        });

        $('#newsletter_form').mousedown(function(e) {
            var clicked = $(e.target);  
            if (clicked.is('.modal') || clicked.parents().is('.modal')) {
                return;
            } else {  
             $('#newsletter_form').hide();
            }
        });
    });


    function isValidEmailAddress(emailAddress) {
       var pattern = /^([a-z\d!#$%&'*+\-\/=?^_`{|}~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]+(\.[a-z\d!#$%&'*+\-\/=?^_`{|}~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]+)*|"((([ \t]*\r\n)?[ \t]+)?([\x01-\x08\x0b\x0c\x0e-\x1f\x7f\x21\x23-\x5b\x5d-\x7e\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]|\\[\x01-\x09\x0b\x0c\x0d-\x7f\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))*(([ \t]*\r\n)?[ \t]+)?")@(([a-z\d\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]|[a-z\d\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF][a-z\d\-._~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]*[a-z\d\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])\.)+([a-z\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]|[a-z\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF][a-z\d\-._~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]*[a-z\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])\.?$/i;
        return pattern.test(emailAddress);
    }
</script>