<?php $columnsLimit = $block->getColumnsLimit() ? : 0; ?>
<?php $_menustatus=$this->helper('Megnor\Category\Helper\Data')->allowExtension();
      $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit);
      $_menu2 = $block->getHtml('level-top', 'mega', $columnsLimit); 
?>

<div class="mobile-dropdown-menu">
    <div class="menu-title">
        <div class="menu-title-inner"><a href="javascript:void(0)" id="shop_by_category_btn">Shop by Category <i class="fa fa-chevron-right"></i></a></div>
   </div>
   <div class="menu mainmenu" id="mobile_mainmenu" style="display: none;">
        <a href="#" class="menu-mobile">Navigation</a>
        <ul class="mobile_cat_nav">
        	<?php /* @escapeNotVerified */ echo strtolower($_menu2); ?>
        </ul>
    </div>
</div>


<script type="text/javascript">
    require([
        'jquery',
        'domReady!'// wait for dom ready
    ], function ($) {

        $( "#shop_by_category_btn" ).click(function() {
            $("#mobile_mainmenu").toggle();
        });

        /*$(".child_menu_btn > a" ).click(function() {
            $(this).parent('.level-top.parent').toggleClass('menu_open').siblings().removeClass('menu_open');
        });*/

    });
</script>